### ISSUE TITLE
Button isn't working.

### ISSUE THREAD

**Issue by koooffa** [barboskinhouse/1course#1]
Во время тестирования игры, запущенной с помощью кнопки "Играть" в главном меню приложения, Ангелина Мышкова заметила баг. 
Отсутствует возможность выхода в главное меню через кнопку в левом верхнем углу.

**Comment by koooffa** [comment]
Ошибка отлажена, Ждём ответа тестировщиков,

**Comment by kott888** [comment]
Ошибка устранена
